# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
[@](fg:#aaaaaa)\
$hostname \
[\uE0B6](fg:#088BB2)\
$os\
$shell\
[\uE0B4](fg:#088BB2) \
[\uE0B6](fg:#FDAA5A)\
$directory\
[\uE0B4](fg:#FDAA5A) \
([\uE0B6](fg:#96275c)\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
[\uE0B4](fg:#96275c))\
$fill\
$status\
$cmd_duration\
$line_break\
$env_var """ # $character

[username]
style_user = "fg:#cccccc"
style_root = "fg:red bold"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
style = "fg:#cccccc"
format = '[$hostname]($style)'
ssh_only = false
disabled = false

[os]
style = "fg:white bg:#088BB2"
format = '[$symbol]($style)'
disabled = false

[os.symbols]
Ubuntu = "îœº "
Fedora = "ïŒŠ "
Debian = "ïŒ† "
Raspbian = "ïŒ• "
Linux = "ï…¼ "
Windows = "î˜ª "
Macos = "ïŒ‚ "
Android = "ï…» "
Pop="ïŒª "
Mint = "ïŒ "
openSUSE = "ïŒ” "
SUSE = "ïŒ” "
Arch = "ïŒƒ "
Manjaro = "ïŒ’ "
EndeavourOS = "ï†—  "
Garuda = "ï¯‘ "
Gentoo = "ïŒ "
Unknown = "ïˆ­ "

[shell]
style = "fg:white bg:#088BB2"
format = '[$indicator ]($style)'
bash_indicator = "î¯Š"
powershell_indicator = "î¯‡" # ó°¨Š
cmd_indicator = "î¯„"
fish_indicator = "ïœ¹" # "ó°ˆº"
disabled = false

[directory]
style = "fg:black bg:#FDAA5A"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"
read_only = " ï ½"
use_os_path_sep = false

[directory.substitutions]
"/cygdrive/c/Users/temig" = "~"
"/cygdrive/c/Users/vboxuser" = "~"
"/home/temig" = "~"
"Documents" = "ïœ˜ "
"Dokumente" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Musik" = "ï€ "
"Pictures" = "ï€¾ "
"Bilder" = "ï€¾ "
"Videos" = "î«™ "
"OneDrive" = "î¢ " # ó°Š

[git_branch]
style = 'fg:white bg:#96275c'
symbol = "ï˜"
format = '[ï„“ $symbol $branch]($style)'

[git_status]
style = 'fg:white bg:#96275c'
format = '[ $all_status$ahead_behind ]($style)'

[cmd_duration]
style = 'fg:#FDAA5A'
format = '[ ï‰’ $duration]($style)'

[status]
style = 'fg:red'
format = '[$symbol ]($style)'
success_symbol = '[îª²](fg:green)' # âœ”
symbol = 'îª‡ ' # âŒ
not_executable_symbol = 'ğŸš«' # ğŸš«
not_found_symbol = 'î­ ' # î©­ ğŸ”
sigint_symbol = 'ï‰– ' # ï‘® ğŸ§±
signal_symbol = 'ó±‹' # âš¡
map_symbol = true
disabled = false

[env_var.SHELL_PROMPT_CHAR]
style = "fg:#ffffff bold"
variable = "SHELL_PROMPT_CHAR"
format = "[$env_value]($style)"
default = "$"
disabled = false

[fill]
symbol = ' '
