# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username[@](green)$hostname \
$os\
$shell\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$status\
$cmd_duration\
$line_break\
$env_var """ # $character

[username]
style_user = "green"
style_root = "green bold"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
style = "green"
format = '[$hostname]($style)'
ssh_only = false
disabled = false

[os]
style = "purple"
disabled = false

[os.symbols]
Ubuntu = "îœº "
Fedora = "ïŒŠ "
Debian = "ïŒ† "
Raspbian = "ïŒ• "
Linux = "ï…¼ "
Windows = "î˜ª "
Macos = "ïŒ‚ "
Android = "ï…» "
Pop="ïŒª "
Mint = "ïŒ "
openSUSE = "ïŒ” "
SUSE = "ïŒ” "
Arch = "ïŒƒ "
Manjaro = "ïŒ’ "
EndeavourOS = "ï†—  "
Garuda = "ï¯‘ "
Gentoo = "ïŒ "
Unknown = "ïˆ­ "

[shell]
style = "blue"
format = '[$indicator ]($style)'
bash_indicator = "î¯Š"
powershell_indicator = "î¯‡" # ó°¨Š
cmd_indicator = "î¯„"
fish_indicator = "ïœ¹" # "ó°ˆº"
disabled = false

[directory]
style = "yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"
read_only = " ï ½"
use_os_path_sep = false

[directory.substitutions]
"/cygdrive/c/Users/temig" = "~"
"/cygdrive/c/Users/vboxuser" = "~"
"/home/temig" = "~"
"Documents" = "ïœ˜ "
"Dokumente" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Musik" = "ï€ "
"Pictures" = "ï€¾ "
"Bilder" = "ï€¾ "
"Videos" = "î«™ "
"OneDrive" = "î¢ " # ó°Š

[git_branch]
symbol = "ï˜"
format = '[$symbol $branch ]($style)'

[git_status]
format = '[$all_status$ahead_behind ]($style)'

[env_var.SHELL_PROMPT_CHAR]
style = "white"
variable = "SHELL_PROMPT_CHAR"
format = "[$env_value]($style)"
default = "$"
disabled = false

[status]
style = 'fg:red'
format = '[$symbol ]($style)'
symbol = 'îª‡ ' # âŒ
not_executable_symbol = 'ğŸš«' # ğŸš«
not_found_symbol = 'î­ ' # î©­ ğŸ”
sigint_symbol = 'ï‰– ' # ï‘® ğŸ§±
signal_symbol = 'ó±‹' # âš¡
map_symbol = true
disabled = false
